// Generated by `npm run art:profile -- --body masculine-v3`. Do not edit by hand.
import fixture from '../procedural/fixtures/masculine.json'
import type { SkeletonProfile } from './profile'

/**
 * masculine-v3, fitted onto humanoid.v1 by `npm run art:fit`.
 *
 * The bones rest axis-aligned, so `semanticskeleton.ts` derives an identity
 * rest-axis correction for every joint here. It carries no weapon and states no
 * `armCarry`: an A-pose rest is not a carry, so the empty-hand one is computed
 * from the rest directions in `procedural/arms.ts`.
 */
export const MASCULINE_PROFILE: SkeletonProfile = {
  name: 'humanoid.v1',
  standingHeight: fixture.standingHeight,
  footprint: fixture.footprint,
  bones: {
    root: 'root',
    pelvis: 'pelvis',
    spine: 'spine',
    chest: 'chest',
    head: 'head',
    'shoulder.l': 'upper_arm_L',
    'elbow.l': 'forearm_L',
    'hand.l': 'hand_L',
    'shoulder.r': 'upper_arm_R',
    'elbow.r': 'forearm_R',
    'hand.r': 'hand_R',
    'hip.l': 'thigh_L',
    'knee.l': 'shin_L',
    'foot.l': 'foot_L',
    'hip.r': 'thigh_R',
    'knee.r': 'shin_R',
    'foot.r': 'foot_R',
  },
  optional: {
    neck: 'neck',
    'clavicle.l': 'clavicle_L',
    'clavicle.r': 'clavicle_R',
  },
  helpers: {
    'shoulder.l': 'shoulder_helper_L',
    'twist.l': 'twist_upper_arm_L',
    'shoulder.r': 'shoulder_helper_R',
    'twist.r': 'twist_upper_arm_R',
  },
}
